language: node_js
node_js:
 - 12.22.7
cache : yarn

services:
-docker
-mysql

install:
  -docker-compose up 
  -docker start

  deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GitHub_token
    on:
      branch: main


