language: node
rvm:
 - 12-alpine

language: generic

services:
  - docker

before_install:
  - docker build -t alpine-node-onbuild .
  - docker build -t alpine-node-onbuild-test tests/
  - docker run -d --name alpine-node-onbuild-test alpine-node-onbuild-test